#!/usr/bin/env php
<?php
if (version_compare("5.6", phpversion()) == 1) {
	echo 'Not support PHP < 5.6';
	exit;
}

if (!is_readable('vendor/autoload.php')) {
	echo 'You should install composer from https://getcomposer.org/ and run ``composer install`` firstly.';
	exit;
}

define('ROOT_PATH', dirname(__FILE__));

require 'vendor/autoload.php';
require './validator/bootstrap.php';