#!/usr/bin/env php
<?php
$zbp = null;
$app = null;
$version = "0.0.1";
if (version_compare("5.6", phpversion()) == 1) {
	echo 'Not support PHP < 5.6';
	exit;
}

if (!is_readable('vendor/autoload.php')) {
	echo 'You should install composer from https://getcomposer.org/ and run ``composer install`` firstly.';
	exit;
}

define('ROOT_PATH', dirname(__FILE__));
define('SERVER_LISTEN_ADDRESS', '127.0.0.1:46214');

require 'vendor/autoload.php';
require './validator/bootstrap.php';